import {
  Banknote,
  Book,
  Briefcase,
  Camera,
  Component,
  Coffee,
  Cpu,
  Gift,
  Globe,
  Heart,
  Home,
  Laptop,
  Monitor,
  Music,
  PenTool,
  Plane,
  Plus,
  Rocket,
  Shield,
  Shirt,
  ShoppingCart,
  Smile,
  Smartphone,
  Star,
  Store,
  Truck,
  Utensils,
  Video,
  Zap,
} from "lucide-react";

export const FORMATTER = new Intl.NumberFormat("es-PE", {
  style: "currency",
  currency: "PEN",
  minimumFractionDigits: 2,
});

export const DATE_FORMATTER = new Intl.DateTimeFormat("es-PE", {
  day: "2-digit",
  month: "short",
  hour: "2-digit",
  minute: "2-digit",
});

export const ICON_GALLERY = {
  store: Store,
  smartphone: Smartphone,
  banknote: Banknote,
  zap: Zap,
  briefcase: Briefcase,
  coffee: Coffee,
  shopping_cart: ShoppingCart,
  monitor: Monitor,
  truck: Truck,
  heart: Heart,
  star: Star,
  gift: Gift,
  car: Truck,
  plane: Plane,
  home: Home,
  utensils: Utensils,
  shirt: Shirt,
  laptop: Laptop,
  smile: Smile,
  shield: Shield,
  component: Component,
  camera: Camera,
  book: Book,
  music: Music,
  video: Video,
  pentool: PenTool,
  globe: Globe,
  cpu: Cpu,
  rocket: Rocket,
  plus: Plus,
};

export const COLOR_GALLERY = [
  "bg-blue-500",
  "bg-emerald-500",
  "bg-rose-500",
  "bg-[#6a1b9a]",
  "bg-amber-500",
  "bg-cyan-500",
  "bg-pink-500",
  "bg-indigo-500",
  "bg-slate-700",
];